apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pytorch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/fguillie/argocd-apps.git
    targetRevision: main
    path: workloads/pytorch
  destination:
    server: https://kubernetes.default.svc
    namespace: pytorch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
