apiVersion: v1
kind: Pod
metadata:
  name: pytorch
spec:
  restartPolicy: OnFailure
  containers:
  - name: pytorch
    image: "nvcr.io/nvidia/pytorch:26.04-py3"
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 360000']
    resources:
      limits:
        nvidia.com/gpu: 1
